✨ feat: 버튼 컴포넌트
likelion-devone/snappy pull request #4
Opened 2022-12-13 03:17 UTC by geekseal

### ▪️ 무엇을 위한 PR인가요?

- [x] 기능 추가 : 버튼 컴포넌트
- [ ] 스타일 :
- [ ] 리팩토링 :
- [ ] 문서 수정 :
- [ ] 버그 수정 :
- [ ] 기타 :

### ▪️ 기대 결과

- 외부 로직에 대응할 수 있는 버튼 컴포넌트 개발

### ▪️ 전달사항

- 페어프로그래밍으로 진행
- 리팩토링 필요

### ▪️ 스크린샷
<img width="329" alt="스크린샷 2022-12-13 오후 12 13 23" src="https://user-images.githubusercontent.com/112453419/207217538-0597d1dd-1f02-49ad-b411-1d17b6da4859.png">
<img width="333" alt="스크린샷 2022-12-13 오후 12 13 36" src="https://user-images.githubusercontent.com/112453419/207217545-3d40a603-0cfa-4d78-8a7d-859e4076f283.png">
<img width="330" alt="스크린샷 2022-12-13 오후 12 13 52" src="https://user-images.githubusercontent.com/112453419/207217547-dc6110b4-70ee-41a8-b1b2-09d92687b258.png">

### ▪️ Issue Number

close : #

2022-12-14 01:07 UTC, custardcream98 requested changes

2022-12-14 01:07 UTC, custardcream98 commented on src/components/common/Clickable/Clickable.jsx
> +export default function Clickable({ children, size, state, callbacks }) {
Button으로 이름을 바꿔도 좋을 것 같아요!

2022-12-14 02:54 UTC, es-kimo commented on src/components/common/Clickable/Clickable.jsx
> +export default function Clickable({ children, size, state, callbacks }) {
수정했습니다.

2022-12-14 06:50 UTC, custardcream98 commented
close : #3

2022-12-14 06:53 UTC, custardcream98 commented
close: #3

2022-12-18 15:45 UTC, custardcream98 approved these changes

2022-12-18 15:45 UTC, custardcream98 commented on src/components/common/Clickable/Clickable.jsx
> +export default function Clickable({ children, size, state, callbacks }) {
```js
Clickable({ children, size, state, callbacks })
```

```js
Clickable({ children, size, state, callbacks, ...props })
```
```js
<StyledButton size={size} state={state} onClick={callbacks[state]} {...props}>
```

2022-12-18 15:45 UTC, merged